// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeSystem.Models;

namespace RecipeSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RecipeSystem.Models.Cuisine", b =>
                {
                    b.Property<int>("CuisineID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CuisineType")
                        .IsRequired();

                    b.HasKey("CuisineID");

                    b.ToTable("Cuisines");
                });

            modelBuilder.Entity("RecipeSystem.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Allergy");

                    b.Property<int?>("CuisineID");

                    b.Property<string>("Difficulty")
                        .IsRequired();

                    b.Property<string>("Directions")
                        .IsRequired();

                    b.Property<string>("Ingredients")
                        .IsRequired();

                    b.Property<string>("Introduction")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTime>("PostingTime");

                    b.Property<int>("Time");

                    b.Property<bool>("Vegetarian");

                    b.HasKey("RecipeID");

                    b.HasIndex("CuisineID");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("RecipeSystem.Models.Recipe", b =>
                {
                    b.HasOne("RecipeSystem.Models.Cuisine", "Cuisine")
                        .WithMany()
                        .HasForeignKey("CuisineID");
                });
#pragma warning restore 612, 618
        }
    }
}
